### ISSUE TITLE
crashing in server tick loop

### ISSUE THREAD

**Issue by ImFlopp** [MyM-ModpackTeam/GalacticScience#206]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 07/06/23 11:58
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: -1
	at hardcorequesting.network.DataReader.readData(DataReader.java:55)
	at hardcorequesting.Team.loadData(Team.java:860)
	at hardcorequesting.QuestingData.loadData(QuestingData.java:634)
	at hardcorequesting.QuestingData.<init>(QuestingData.java:519)
	at hardcorequesting.QuestingData.readAllData(QuestingData.java:503)
	at hardcorequesting.QuestingData$1.read(QuestingData.java:409)
	at hardcorequesting.network.FileHelper.loadData(FileHelper.java:107)
	at hardcorequesting.QuestingData.load(QuestingData.java:438)
	at hardcorequesting.WorldEventListener.onLoad(WorldEventListener.java:23)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_578_WorldEventListener_onLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2090132200 bytes (1993 MB) / 3111649280 bytes (2967 MB) up to 7039090688 bytes (6713 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx7552m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAA	OpenComputers|Core{1.7.5.1290} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAA	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCHIJAA	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9-CUSTOM_1.jar) 
	UCHIJAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAA	armourersWorkshop{1.7.10-0.48.5} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.48.5.jar) 
	UCHIJAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAA	AwesomeSauceCore{0.1.0} [AwesomeSauce Core] (AwesomeSauceCore-1.7.x-b52.jar) 
	UCHIJAA	AwesomeSauceComponents{0.1.0} [AwesomeSauce Components] (AwesomeSauceCore-1.7.x-b52.jar) 
	UCHIJAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAA	betterstorage{0.13.1.128} [BetterStorage] (BetterStorage-1.7.10-0.13.1.128.jar) 
	UCHIJAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAA	CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.2 - MC 1.7.10.jar) 
	UCHIJAA	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHIJAA	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCHIJAA	thedalekmod{39.75} [The Dalek Mod] (Dalek_Mod_1710.jar) 
	UCHIJAA	darkcore{0.41} [Dark Core] (darkcore-0.41-179.jar) 
	UCHIJAA	defaultkeys{1.0.28} [Default Keyconfig] (defaultkeys-mc1.7.10-1.0.28.jar) 
	UCHIJAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAA	DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
	UCHIJAA	dimstorage{1.3} [DimStorage] (DimStorage-1.7.2-1.3.jar) 
	UCHIJAA	Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.14.2.jar) 
	UCHIJAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAA	exnihilo{1.38-53} [Ex Nihilo] (Ex-Nihilo-1.38-53.jar) 
	UCHIJAA	exastrisrebirth{MC1.7.10-1.01-null} [Ex Astris Rebirth] (Ex-Astris-Rebirth-MC1.7.10-1.01-null.jar) 
	UCHIJAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAA	FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
	UCHIJAA	FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
	UCHIJAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJAA	GalacticScience_Tweaks{1.4} [GalacticScience-Tweaks] (GalacticScience_Tweaks-1.6.jar) 
	UCHIJAA	minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
	UCHIJAA	advgenerators{0.9.20.123} [Advanced Generators] (generators-0.9.20.123-mc1.7.10.jar) 
	UCHIJAA	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
	UCHIJAA	hardcoremapreset{2.2.0} [HardcoreMapReset] (HardCoreMapReset-2.2.0.jar) 
	UCHIJAA	HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar) 
	UCHIJAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAA	launchgui{1.7.10-2.0-18} [LaunchGUI] (LaunchGui-1.7.10-2.0-18-client.jar) 
	UCHIJAA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJAA	NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	Netherless{0.9.0} [Netherless] (Netherless-0.9.0.jar) 
	UCHIJAA	NuclearCraft{1.9g} [NuclearCraft] (NuclearCraft-1.9g--1.7.10.jar) 
	UCHIJAA	OpenComputers{1.7.5.1290} [OpenComputers] (OpenComputers-MC1.7.10-1.7.5.1290-universal.jar) 
	UCHIJAA	OpenAutomation{1.7.x-b218} [OpenAutomation] (OpenAutomation-1.7.x-b218.jar) 
	UCHIJAA	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
	UCHIJAA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.35.jar) 
	UCHIJAA	quantumflux{1.7.10-1.3.4} [QuantumFlux] (QuantumFlux-1.7.10-1.3.4.jar) 
	UCHIJAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAA	RefinedRelocation{1.1.34} [Refined Relocation] (RefinedRelocation-mc1.7.10-1.1.34.jar) 
	UCHIJAA	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCHIJAA	rftools{4.23} [RFTools] (rftools-4.23.jar) 
	UCHIJAA	RouterReborn{1.2.0.43} [Router Reborn] (RouterReborn-1.7.10-1.2.0.43-universal.jar) 
	UCHIJAA	SGCraft{1.13.3} [Greg's SG Craft] (SGCraft-1.13.3-mc1.7.10.jar) 
	UCHIJAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAA	superMassiveTech{MC1.7.10-0.4.0-alpha-114} [Super Massive Tech] (SuperMassiveTech-MC1.7.10-0.4.0-beta-114.jar) 
	UCHIJAA	TardisMod{0.995} [Tardis Mod] (tardismod-1.7.10-0.995-350.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Mantle Environment: Environment healthy.
	CoFHCore: -[1.7.10]3.1.4-329
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from tardismod-1.7.10-0.995-350.jar
		* armourersWorkshopAPI (1.7.10-10.13.4.1448-1.7.10) from Armourers-Workshop-1.7.10-0.48.5.jar
		* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.10-1.3.3-17.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8.2 - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.43-universal.jar
		* CoFHAPI|block (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-null.jar
		* CoFHAPI|core (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-null.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from ElectricalAge-1.14.2.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|inventory (1.7.10R1.1.0) from NuclearCraft-1.9g--1.7.10.jar
		* CoFHAPI|item (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.43-universal.jar
		* CoFHAPI|tileentity (1.7.10R1.1.0) from ProgressiveAutomation-1.7.10-1.6.35.jar
		* CoFHAPI|transport (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.43-universal.jar
		* CoFHAPI|world (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-null.jar
		* CoFHLib (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|audio (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|container (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|slot (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render|particle (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|helpers (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|position (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world|feature (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* ComputerCraft|API (1.75) from tardismod-1.7.10-0.995-350.jar
		* ComputerCraft|API|FileSystem (1.75) from tardismod-1.7.10-0.995-350.jar
		* ComputerCraft|API|Lua (1.75) from tardismod-1.7.10-0.995-350.jar
		* ComputerCraft|API|Media (1.75) from tardismod-1.7.10-0.995-350.jar
		* ComputerCraft|API|Peripheral (1.75) from tardismod-1.7.10-0.995-350.jar
		* ComputerCraft|API|Permissions (1.75) from tardismod-1.7.10-0.995-350.jar
		* ComputerCraft|API|Redstone (1.75) from tardismod-1.7.10-0.995-350.jar
		* ComputerCraft|API|Turtle (1.75) from tardismod-1.7.10-0.995-350.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* Galacticraft API (1.1) from GalacticraftCore-1.7-3.0.12.504.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* McJtyLib (1.8.1) from mcjtylib-1.8.1.jar
		* MekanismAPI|core (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* MekanismAPI|energy (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* MekanismAPI|gas (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* MekanismAPI|infuse (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* MekanismAPI|laser (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* MekanismAPI|reactor (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* MekanismAPI|recipe (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* MekanismAPI|transmitter (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* MekanismAPI|util (9.0.0) from NuclearCraft-1.9g--1.7.10.jar
		* minechemAPI (1.7.10R1) from Minechem-1.7.10-5.0.5.406.jar
		* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.6.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
		* RefinedRelocationAPI (1.0.0) from RefinedRelocation-mc1.7.10-1.1.34.jar
		* Thaumcraft|API (4.2.2.0) from Ex-Astris-Rebirth-MC1.7.10-1.01-null.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from ElectricalAge-1.14.2.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Modpack Version: 1.6.10
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Armourer's Workshop: 
		Render Type: MODEL_ATTACHMENT
		Texture Render: false
		Baking Queue: 0
		Request Queue: 0
		Texture Painting: true
		Multipass Skin Rendering: true
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ImFlopp** [comment]
It also crashes when loading a specific [world](https://www.mediafire.com/file/hj28qlfw4em2cs0/the_world_that_actually_crashes%252C_can_you_imagine_that.zip/file)
