### ISSUE TITLE
Crash on 1.4.12 - possible interaction between transfer node and reaction chamber

### ISSUE THREAD

**Issue by alyandon** [MyM-ModpackTeam/GalacticScience#36]
Here it is in all its glory.  I placed a NuclearCraft reaction chamber in the wrong place and I suspect a transfer node full of minechem hydrogen cells connected to it.  I get the same crash every time I try and load the world.

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 10/29/15 9:04 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 2
	at com.nr.mod.blocks.tileentities.TileEntityInventory.func_70301_a(TileEntityInventory.java:47)
	at com.rwtema.extrautils.tileentity.transfernodes.nodebuffer.ItemBuffer.transfer(ItemBuffer.java:41)
	at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeBase.transferItems(PipeBase.java:48)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.transferItems(TileEntityTransferNode.java:592)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.handleInventories(TileEntityTransferNode.java:432)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNodeInventory.processBuffer(TileEntityTransferNodeInventory.java:150)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.func_145845_h(TileEntityTransferNode.java:145)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.nr.mod.blocks.tileentities.TileEntityInventory.func_70301_a(TileEntityInventory.java:47)
	at com.rwtema.extrautils.tileentity.transfernodes.nodebuffer.ItemBuffer.transfer(ItemBuffer.java:41)
	at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeBase.transferItems(PipeBase.java:48)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.transferItems(TileEntityTransferNode.java:592)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.handleInventories(TileEntityTransferNode.java:432)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNodeInventory.processBuffer(TileEntityTransferNodeInventory.java:150)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.func_145845_h(TileEntityTransferNode.java:145)

-- Block entity being ticked --
Details:
	Name: TileEntityTransferNodeInventory // com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNodeInventory
	Block type: ID #622 (tile.extrautils:extractor_base // com.rwtema.extrautils.tileentity.transfernodes.BlockTransferNode)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-15,58,195), Chunk: (at 1,3,3 in -1,12; contains blocks -16,0,192 to -1,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #622 (tile.extrautils:extractor_base // com.rwtema.extrautils.tileentity.transfernodes.BlockTransferNode)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [GCEntityPlayerMP['alyandon'/8, l='New World', x=-12.92, y=58.00, z=197.69]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -3807610037365705164
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 901113912 bytes (859 MB) / 1486880768 bytes (1418 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAAAA	Aroma1997Core{1.0.2.14} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.14.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHIJAAAAAAAAA	notimefix{2.1.0} [No Time Fix] (minecraft.jar) 
	UCHIJAAAAAAAAA	OpenComputers|Core{1.5.14.30} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAAAAAAA	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.345.jar) 
	UCHIJAAAAAAAAA	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) 
	UCHIJAAAAAAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAAAAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAAAAAAA	armourersWorkshop{1.7.10-0.36.0.92} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.36.0.92.jar) 
	UCHIJAAAAAAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.36.0.92.jar) 
	UCHIJAAAAAAAAA	Aroma1997CoreHelper{1.0.2.14} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.14.jar) 
	UCHIJAAAAAAAAA	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) 
	UCHIJAAAAAAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAAAAAAA	AwesomeSauceCore{0.1.0} [AwesomeSauce Core] (AwesomeSauceCore-1.7.x-b52.jar) 
	UCHIJAAAAAAAAA	AwesomeSauceComponents{0.1.0} [AwesomeSauce Components] (AwesomeSauceCore-1.7.x-b52.jar) 
	UCHIJAAAAAAAAA	bdlib{1.9.1.97} [BD Lib] (bdlib-1.9.1.97-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-11.jar) 
	UCHIJAAAAAAAAA	bookshelf{1.1.2} [Bookshelf] (Bookshelf-1.7.10-1.1.2.jar) 
	UCHIJAAAAAAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJAAAAAAAAA	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAAAAAAA	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAAAAAAA	CustomMainMenu{1.6} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.6.jar) 
	UCHIJAAAAAAAAA	darkcore{0.25} [Dark Core] (darkcore-0.25-35.jar) 
	UCHIJAAAAAAAAA	ImmibisCore{59.1.1} [Immibis Core] (immibis-core-59.1.1.jar) 
	UCHIJAAAAAAAAA	DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
	UCHIJAAAAAAAAA	dimstorage{1.3} [DimStorage] (DimStorage-1.7.2-1.3.jar) 
	UCHIJAAAAAAAAA	Eln{50} [Electrical Age] (ElectricalAge_BETA-1.10_r50.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAAAAAAA	exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) 
	UCHIJAAAAAAAAA	exastris{1.15} [Ex Astris] (Ex-Astris-1.15.jar) 
	UCHIJAAAAAAAAA	ExtraUtilities{1.2.8} [Extra Utilities] (extrautilities-1.2.8.jar) 
	UCHIJAAAAAAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.345.jar) 
	UCHIJAAAAAAAAA	GalacticScience_Tweaks{1.0} [GalacticScience-Tweaks] (GalacticScience_Tweaks-1.1.jar) 
	UCHIJAAAAAAAAA	minechem{5.0.5.398} [Minechem] (Minechem-1.7.10-5.0.5.398.jar) 
	UCHIJAAAAAAAAA	advgenerators{0.9.16.99} [Advanced Generators] (generators-0.9.16.99-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	hardcoremapreset{2.2.0} [HardcoreMapReset] (HardCoreMapReset-2.2.0.jar) 
	UCHIJAAAAAAAAA	HardcoreQuesting{The Journey (4.2.4)} [Hardcore Questing Mode] (HQM-The Journey (4.2.4).jar) 
	UCHIJAAAAAAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAAAAAAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAAAAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAAAAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAAAAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAAAAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHIJAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAAAAAAA	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C [Edited].jar) 
	UCHIJAAAAAAAAA	modtweaker2{0.8.2} [Mod Tweaker 2] (ModTweaker 2-0.8.1.jar) 
	UCHIJAAAAAAAAA	modularsystemsapi{0.0.1} [Modular Systems API] (Modular Systems-1.7.10-1.7.3.jar) 
	UCHIJAAAAAAAAA	modularsystems{1.7.3} [Modular Systems] (Modular Systems-1.7.10-1.7.3.jar) 
	UCHIJAAAAAAAAA	NEIAddons{1.12.7.21} [NEI Addons] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAAAAAAA	NEIAddons|AppEng{1.12.7.21} [NEI Addons: Applied Energistics 2] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAAAAAAA	NEIAddons|Botany{1.12.7.21} [NEI Addons: Botany] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAAAAAAA	NEIAddons|Forestry{1.12.7.21} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAAAAAAA	NEIAddons|CraftingTables{1.12.7.21} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAAAAAAA	NEIAddons|ExNihilo{1.12.7.21} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAAAAAAA	Netherless{0.9.0} [Netherless] (Netherless-0.9.0.jar) 
	UCHIJAAAAAAAAA	NuclearCraft{0.0.1.5} [NuclearCraft] (NuclearCraft-0.0.1.5--1.7.10.jar) 
	UCHIJAAAAAAAAA	OpenComputers{1.5.14.30} [OpenComputers] (OpenComputers-MC1.7.10-1.5.14.30-universal.jar) 
	UCHIJAAAAAAAAA	OpenAutomation{1.7.x-b218} [OpenAutomation] (OpenAutomation-1.7.x-b218.jar) 
	UCHIJAAAAAAAAA	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) 
	UCHIJAAAAAAAAA	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) 
	UCHIJAAAAAAAAA	progressiveautomation{1.6.27} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.27.jar) 
	UCHIJAAAAAAAAA	quantumflux{1.7.10-1.3.0-b2} [QuantumFlux] (QuantumFlux-1.7.10-1.3.0-b2.jar) 
	UCHIJAAAAAAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAAAAAAAAA	RefinedRelocation{1.0.8b} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.8b.jar) 
	UCHIJAAAAAAAAA	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) 
	UCHIJAAAAAAAAA	rftools{2.80} [RFTools] (rftools-2.80.jar) 
	UCHIJAAAAAAAAA	RouterReborn{1.2.0.31} [Router Reborn] (RouterReborn-1.7.10-1.2.0.31-universal.jar) 
	UCHIJAAAAAAAAA	SGCraft{1.9.3} [Greg's SG Craft] (SGCraft-1.9.3-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	SolarFlux{1.7.10-0.8a} [Solar Flux] (SolarFlux-1.7.10-0.8a.jar) 
	UCHIJAAAAAAAAA	superMassiveTech{0.2.0-alpha} [Super Massive Tech] (SuperMassiveTech-MC1.7.10-0.2.0-alpha-86.jar) 
	UCHIJAAAAAAAAA	TardisMod{0.985} [Tardis Mod] (tardismod-1.7.10-0.985-150.jar) 
	UCHIJAAAAAAAAA	thedalekmod{39.51} [The Dalek Mod] (the_dalek_mod_1.7.10.zip) 
	UCHIJAAAAAAAAA	yampst{1.3.5} [YAMPST] (Yampst-gs-1.4.0.jar) 
	UCHIJAAAAAAAAA	zyinhud{1.3.9} [Zyin's HUD] (ZyinsHUD-(1.7.10)-v.1.3.9.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: Environment healthy.
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from tardismod-1.7.10-0.985-150.jar
		* armourersWorkshopAPI (1.7.10-10.13.4.1448-1.7.10) from Armourers-Workshop-1.7.10-0.36.0.92.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.8.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.8.jar
		* ChiselAPI (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.4.1.40.jar
		* CoFHAPI (1.7.10R1.0.2) from Bookshelf-1.7.10-1.1.2.jar
		* CoFHAPI|block (1.7.10R1.0.2) from AwesomeSauceCore-1.7.x-b52.jar
		* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|energy (1.7.10R1.0.13) from ProgressiveAutomation-1.7.10-1.6.27.jar
		* CoFHAPI|fluid (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.31-universal.jar
		* CoFHAPI|inventory (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.31-universal.jar
		* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.10) from NuclearCraft-0.0.1.5--1.7.10.jar
		* CoFHAPI|tileentity (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|transport (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|world (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.31-universal.jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.345.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* minechemAPI (1.7.10R1) from Minechem-1.7.10-5.0.5.398.jar
		* OpenBlocks|API (1.0) from OpenBlocks-1.7.10-1.4.3.jar
		* OpenComputersAPI|Component (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Core (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Driver (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Driver|Item (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Event (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|FileSystem (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Internal (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Machine (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Manual (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Network (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Prefab (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* RefinedRelocationAPI (1.0.0) from RefinedRelocation-1.7.10-1.0.8b.jar
		* Thaumcraft|API (4.2.2.0) from tardismod-1.7.10-0.985-150.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Modpack Version: 1.4.12
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['alyandon'/8, l='New World', x=-12.92, y=58.00, z=197.69]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Bennyboy1695** [comment]
Yeah the transfer node is causing it, its not liking interacting with the reactor. Only way you'll be able to join again is if you remove the node first

**Comment by NolanSyKinsley** [comment]
you should be able to load the r.-1.0.mca file from your save into mcedit . Then tell mcedit to go to block -15,58,195 and it should have the node highlighted, just delete it, save and replace the file.

**Comment by alyandon** [comment]
Yeah, it isn't a big deal as I already recovered my world with mcedit.  You think this is worth reporting to ExU or NC?

**Comment by drz2k** [comment]
To NC probably, the dev is listening to bugs :)

**Comment by SirWilli** [comment]
It would be great if you can try to reproduce the bug in a new world with the latest versions of extra utilties and nuclearcraft and if it still crashes then report it to them.

**Comment by alyandon** [comment]
@SirWilli do you mean update the mods in the modpack or literally create an instance with only those two mods installed to test their interaction?

**Comment by SirWilli** [comment]
Update them in the modpack

**Comment by alyandon** [comment]
Alright, I'll do that and test and get back to you sometime later this weekend.

**Comment by alyandon** [comment]
Updated modpack to 1.4.13 and installed ExtraUtilities 1.2.12.  NuclearCraft doesn't have a newer release than 0.0.1.5 available.

After some experimentation in a test world, I discovered you can connect a transfer node to a reaction generator without immediately causing a crash.  However, as soon as you attempt to insert anything into the reaction generator (either via transfer node connected to transfer pipe or directly connected to the transfer node) the game crashes with the same error.

**Comment by drz2k** [comment]
I think its on the NC mod part...

**Comment by alyandon** [comment]
Yeah, looking over the most recent posts on the curse forums it appears that the vanilla hopper also causes the same crash.

**Comment by SirWilli** [comment]
Ok, thanks for testing it. Did you report it to the mod author?

**Comment by alyandon** [comment]
Done.  http://minecraft.curseforge.com/projects/nuclearcraft-mod?comment=120

**Comment by drz2k** [comment]
Thanks for reporting it, NC flagged to check for updates on next gs update.
