### ISSUE TITLE
Oxygen sealer crashes game upon entering

### ISSUE THREAD

**Issue by slayatrump** [MyM-ModpackTeam/GalacticScience#81]
I dont know why, but it just keeps crashing upon the entrance of my world.  Even after updating to the update that "fixes" it, this must be a different reason for it to crash the game.

Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 1/14/16 4:01 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:359)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:92)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:47)
	at micdoodle8.mods.galacticraft.core.oxygen.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:64)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_145845_h(TileEntityOxygenSealer.java:163)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:359)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:92)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:47)
	at micdoodle8.mods.galacticraft.core.oxygen.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:64)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_145845_h(TileEntityOxygenSealer.java:163)

-- Block entity being ticked --
Details:
	Name: Air Sealer // micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer
	Block type: ID #183 (tile.sealer // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenSealer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-7,59,188), Chunk: (at 9,3,12 in -1,11; contains blocks -16,0,176 to -1,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #183 (tile.sealer // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenSealer)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by SirWilli** [comment]
You have to manually update galacticraft or wait for the next modpack update

**Comment by slayatrump** [comment]
can i ask how do i do that?

**Comment by SirWilli** [comment]
Downlaod latest 1.7.10 files here: http://www.micdoodle8.com/mods/galacticraft/downloads
and replace the 3 files with your other 3 files in your mods folder.

**Comment by slayatrump** [comment]
thanks, works smoothly now!
